// <auto-generated />
using ListPriceGeneralAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListPriceGeneralAPI.Migrations
{
    [DbContext(typeof(PriceListDbContext))]
    [Migration("20220910093502_Db Initialized")]
    partial class DbInitialized
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ListPriceGeneralAPI.Models.Item", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemName");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
